### PR TITLE
Adopt VAPI to Tox upstream git.

### PR DESCRIPTION
**Pull request by drahnr**
Fixes compilation errors.

### CODE REVIEW

**Comment by urras** [comment]
Good luck getting this merged, @naxuroqa hasn't been seen for months.

**Comment by stal888** [comment]
Press F to pay respects

**Comment by hexafluoride** [comment]
F

**Comment by markus1540** [comment]
F

**Comment by mannol** [comment]
F

**Comment by naxuroqa** [comment]
closed because outdated

**Pull request closed without merging**
